blank_issues_enabled: true
contact_links:
  - name: Feature Requests
    url: https://github.com/LEGO/api-management-management-api/discussions/categories/feature-requests
    about: Feature requests and ideas for AMMA, API Gateway & Event Broker
  - name: Support, Questions & Answers
    url: https://github.com/LEGO/api-management-management-api/discussions/categories/q-a
    about: If you need help, this is the place to be
